### ISSUE TITLE
TarTool as a Chocolatey package

### ISSUE THREAD

**Issue by ferventcoder** [petabridge/spark-installer-windows#2]
First example

![image](https://cloud.githubusercontent.com/assets/63502/20864307/ecfb09b6-b9b0-11e6-800d-73b2792fe867.png)

**Comment by ferventcoder** [comment]
This is all the logic required:

~~~powershell
$ErrorActionPreference = 'Stop';

$packageName  = 'TarTool'
$toolsDir     = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"
$fileLocation = Join-Path $toolsDir 'TarTool.zip'

$packageArgs = @{
  packageName   = $packageName
  file          = $fileLocation
  destination   = $toolsDir
}

# If the version of Chocolatey is less than 0.10.1, Get-ChocolateyUnzip needs `fileFullPath`.
if ((New-Object System.Version $env:CHOCOLATEY_VERSION) -le (New-Object System.Version '0.10.0')) {
  $packageArgs["fileFullPath"] = $fileLocation
}

Get-ChocolateyUnzip @packageArgs
~~~

**Comment by ferventcoder** [comment]
If I was downloading it from the internet, I would have called [`Install-ChocolateyZipPackage`](https://chocolatey.org/docs/helpers-install-chocolatey-zip-package) instead with the package url and a sha256 checksum. This particular tool has a GPL license that allows redist, and it is tiny at 90K.

**Comment by ferventcoder** [comment]
https://chocolatey.org/packages/tartool

![image](https://cloud.githubusercontent.com/assets/63502/20864329/f21079f8-b9b1-11e6-9d56-dba2e1458214.png)

**Comment by ferventcoder** [comment]
So you may start to see why Chocolatey is an extremely powerful framework.

* Completely decentralized, so packages can be internal or somewhere like the community repository (https://chocolatey.org/packages).
* It is a framework completely designed to help you get software onto machines and configured, managing the entire software lifecycle.
* It has features for downloading remote files when necessary. 
* It has over 30+ built-in functions that simplify complex tasks, sometimes into one line function calls.

**Comment by ferventcoder** [comment]
For TarTool

* I added or downloaded some executable to the package directory itself.
* Chocolatey automatically shimmed the tool making it available on the path immediately for use - https://chocolatey.org/docs/features-shim
* What you may not see - Chocolatey also reloads paths between packages and allows me to do it within the same package with `Update-Session`. It also notices environment variable changes and tells me I should run `refreshenv` to reload the environment in my current shell.

**Comment by ferventcoder** [comment]
Chocolatey does a whole bunch of other great things you would expect a tool that has been around for over five years to be able to do.

**Comment by ferventcoder** [comment]
Here's the whole package for tartool - https://github.com/ferventcoder/chocolatey-packages/tree/master/manual/tartool

Now one just needs an updated hadoop package.

Then you could create a spark package that takes a dependency on jdk8, tartool, and hadoop (I admit I haven't fully looked over which is required in what order in your script).

**Comment by ferventcoder** [comment]
If you want to try one out for yourself, grab the latest version of Chocolatey and run `choco new pkgname` and then take a look at the output. Most of what you need to do is in the default template's output and provides what we call "just in time documentation". HTH.

**Comment by Aaronontheweb** [comment]
@ferventcoder this is awesome! I'll give it a try.

**Comment by heynickc** [comment]
FYI, merged PR #8 related to making this script runnable via `choco install` is being affected by this open issue with chocolatey https://github.com/chocolatey/choco/issues/1016.  When users run `choco install spark-installer-windows` they will see stderr format of what should be stdout of the installation script.

**Comment by ferventcoder** [comment]
Just FYI - `-windows` is a bit redundant in the package name. As is `-installer`. The software that is installed is `spark`? Probably best to just call the package `spark`.

**Comment by ferventcoder** [comment]
So really, the thinking here is create a package for tartool, create a package for hadoop (or work on upping one of the existing ones), and create a package for spark.

**Comment by ferventcoder** [comment]
Hope this helps. Let me know if you are curious on how this should look.

**Comment by Aaronontheweb** [comment]
@ferventcoder there's another "spark" package for some unrelated tool, so we've renamed this to "apache-spark"

**Comment by Aaronontheweb** [comment]
@ferventcoder might also be not a bad idea for us to split spark and mobius in the future. The Hadoop binaries are bundled with the Spark distribution as a single package so it'd be a challenge to break those down into separate components (all .jars are in the same tar file.)

**Comment by ferventcoder** [comment]
`apache-spark` sounds perfect to me 👍
